name: .NET build

on: push

env:
  PACKAGE_SOURCE: github

jobs:
  pre_job:
    runs-on: ubuntu-20.04
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: 'same_content_newer'
          skip_after_successful_duplicate: 'false'

  build:
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'
    runs-on: ubuntu-20.04

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup and cache dependencies
      uses: cyber-crypt-com/build-setup-action@master

    - name: Login into package feed
      run: |
        dotnet nuget add source --username cybot-cc --password ${{ secrets.CYBOT_TOKEN }} --store-password-in-clear-text --name ${{ env.PACKAGE_SOURCE }} "https://nuget.pkg.github.com/cybercryptio/index.json"

    - name: Install XmlDocMarkdown
      run: dotnet tool install xmldocmd -g

    - name: Build
      run: make build

    - name: Test
      run: make tests

    - name: Verify API docs are up-to-date
      run: make apidocs-verify

    - name: Install GitVersion
      if: ${{ github.ref_name == 'master' || github.ref_type == 'tag' }}
      uses: gittools/actions/gitversion/setup@v0.9.13
      with:
        versionSpec: '5.x'

    - name: Determine Version
      if: ${{ github.ref_name == 'master' || github.ref_type == 'tag' }}
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.13
      with:
        additionalArguments: '/overrideconfig mode=ContinuousDeployment'

    - name: Create tag
      if: ${{ github.ref_name == 'master' }}
      run: |
        git tag -f ${{ steps.gitversion.outputs.semVer }}
        git push origin ${{ steps.gitversion.outputs.semVer }}

    - name: Publish
      if: ${{ github.ref_name == 'master' || github.ref_type == 'tag' }}
      run: make nuget-publish
      env:
        PACKAGE_SOURCE: https://api.nuget.org/v3/index.json
        API_KEY: ${{ secrets.NUGET_API_KEY }}
        VERSION: ${{ github.ref_name }}