name: Release

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

env:
  PACKAGE_SOURCE: github

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Setup and cache dependencies
      uses: cyber-crypt-com/build-setup-action@master

    - name: Login into package feed
      run: |
        dotnet nuget add source --username cybot-cc --password ${{ secrets.CYBOT_TOKEN }} --store-password-in-clear-text --name ${{ env.PACKAGE_SOURCE }} "https://nuget.pkg.github.com/cybercryptio/index.json"

    - name: Build
      run: make build

    - name: Publish
      run: make nuget-publish
      env:
        API_KEY: ${{ secrets.CYBOT_TOKEN }}
        VERSION: ${{ github.ref_name }}